### ISSUE TITLE
Errant JA3 fingerprints

### ISSUE THREAD

**Issue by 89z** [dreadl0ck/netcap-dbs#1]
I noticed here [1] you have these links [2][3]. I reviewed these files, and I think I found a problem. In the file `getAllUasJson`, one of the popular entries is this one:

~~~json
{
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
   "Count": 467031,
   "md5": "182ba821a28a15ba60af732fe371be36",
   "Last_seen": "2021-07-29 03:06:27"
}
~~~

Which is an entry for Chrome 85 on Windows 10. You can cross reference to the other file, to get the JA3:

~~~json
{
   "md5": "182ba821a28a15ba60af732fe371be36",
   "ja3": "771,49196-49195-49200-49199-159-158-49188-49187-49192-49191-49162-49161-49172-49171-157-156-61-60-53-47-10,0-10-11-13-35-23-65281,,",
   "First_reported": "2019-08-05 02:21:06"
}
~~~

The issue I am having with this JA3, is that the last two fields are empty (EllipticCurve,EllipticCurvePointFormat). I tried different combinations, but I cant actually make a successful request using a TLS hello such as that. Have you had an experience with that?

1. https://github.com/dreadl0ck/netcap-dbs#ja3-fingerprints-and-useragents-from-ja3ercom
2. https://ja3er.com/getAllUasJson
3. https://ja3er.com/getAllHashesJson

**Comment by 89z** [comment]
After more looking, I found this entry with an identical User-Agent:

~~~json
{
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
   "Count": 21350,
   "md5": "46346146986ace52994f40a34f06b1ce",
   "Last_seen": "2021-02-26 16:43:43"
}
~~~

and the cross reference:

~~~json
{
   "md5": "46346146986ace52994f40a34f06b1ce",
   "ja3": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53-255,0-11-10-35-5-16-23-13-43-45-51,23-24,0-1-2",
   "First_reported": "2020-05-25 15:46:11"
}
~~~

in this case, the cross reference has all fields listed, as expected. I am not sure what is causing the missing fields in some cases.

**Comment by dreadl0ck** [comment]
These fields can be empty when the client does not make use of TLS extensions.

From the salesforce blog post (https://engineering.salesforce.com/open-sourcing-ja3-92c9e53c3c41):

```
The field order is as follows:
SSLVersion,Ciphers,Extensions,EllipticCurves,EllipticCurvePointFormats

Example:
769,47–53–5–10–49161–49162–49171–49172–50–56–19–4,0–10–11,23–24–25,0

If there are no SSL Extensions in the Client Hello, the fields are left empty.

Example:
769,4–5–10–9–100–98–3–6–19–18–99,,,
```

TLS 1.2 extensions are defined in this RFC: https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.1.4

**Comment by 89z** [comment]
Right, so if extensions are empty, then curves can be empty too. Also I have found that extensions can be listed, but if Extension 10 (supported_groups) is listed, then curves need to be provided. Thats why I raised the issue, as the JA3 in the original post, lists Extension 10, but then provides no curves, so it seems that the JA3 is invalid in that case.

**Comment by dreadl0ck** [comment]
Good catch! Might be worth to report to the ja3er maintainers to see what they think about this.

Ja3 does not care about spec compliance though, the goal is to produce a hash also for every handshake encountered.

Otherwise such detection mechanisms could be evaded easily by intentionally violating the spec with a slightly malformed packet. A spec compliant server might reject it, but nothing stops you from hosting a CC server with a modified TLS implementation.
